name: Build Docker Image

on:
  push:  # Trigger on any push to any branch
    branches: [main, dev]  # Specify branches if desired

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  # Path to Dockerfile
          file: ./Dockerfile  # Name of Dockerfile
          push: true  # Push the image to a registry
          tags: ${{ github.repository }}:${{ github.sha }}  # Tag with repo name and commit SHA
          #platforms: linux/amd64, linux/arm64  # Build for multiple platforms (optional)

